import type { Philosopher } from './types';

/** Curated catalog of famous philosophers (330 entries). Slugs are 5–8 lowercase letters. */
export const PHILOSOPHER_CATALOG: readonly Philosopher[] = [
  { slug: 'plato', displayName: 'Plato' },
  { slug: 'socrat', displayName: 'Socrates' },
  { slug: 'aristo', displayName: 'Aristotle' },
  { slug: 'thales', displayName: 'Thales' },
  { slug: 'anaxim', displayName: 'Anaximander' },
  { slug: 'anaxag', displayName: 'Anaxagoras' },
  { slug: 'heracl', displayName: 'Heraclitus' },
  { slug: 'parmen', displayName: 'Parmenides' },
  { slug: 'empedo', displayName: 'Empedocles' },
  { slug: 'democr', displayName: 'Democritus' },
  { slug: 'protag', displayName: 'Protagoras' },
  { slug: 'gorgia', displayName: 'Gorgias' },
  { slug: 'hippia', displayName: 'Hippias' },
  { slug: 'prodic', displayName: 'Prodicus' },
  { slug: 'antist', displayName: 'Antisthenes' },
  { slug: 'diogen', displayName: 'Diogenes of Sinope' },
  { slug: 'crates', displayName: 'Crates of Thebes' },
  { slug: 'zenodo', displayName: 'Zeno of Citium' },
  { slug: 'cleant', displayName: 'Cleanthes' },
  { slug: 'chrysi', displayName: 'Chrysippus' },
  { slug: 'epicur', displayName: 'Epicurus' },
  { slug: 'lucret', displayName: 'Lucretius' },
  { slug: 'cicero', displayName: 'Cicero' },
  { slug: 'seneca', displayName: 'Seneca' },
  { slug: 'epictet', displayName: 'Epictetus' },
  { slug: 'marcus', displayName: 'Marcus Aurelius' },
  { slug: 'plotin', displayName: 'Plotinus' },
  { slug: 'porphy', displayName: 'Porphyry' },
  { slug: 'iambli', displayName: 'Iamblichus' },
  { slug: 'procli', displayName: 'Proclus' },
  { slug: 'simpli', displayName: 'Simplicius' },
  { slug: 'hypati', displayName: 'Hypatia' },
  { slug: 'boethi', displayName: 'Boethius' },
  { slug: 'august', displayName: 'Augustine of Hippo' },
  { slug: 'anselm', displayName: 'Anselm of Canterbury' },
  { slug: 'abelar', displayName: 'Peter Abelard' },
  { slug: 'avice', displayName: 'Avicenna' },
  { slug: 'averro', displayName: 'Averroes' },
  { slug: 'maimon', displayName: 'Maimonides' },
  { slug: 'albert', displayName: 'Albertus Magnus' },
  { slug: 'aquina', displayName: 'Thomas Aquinas' },
  { slug: 'bonave', displayName: 'Bonaventure' },
  { slug: 'ockham', displayName: 'William of Ockham' },
  { slug: 'wyclif', displayName: 'John Wycliffe' },
  { slug: 'erasmu', displayName: 'Erasmus' },
  { slug: 'luther', displayName: 'Martin Luther' },
  { slug: 'calvin', displayName: 'John Calvin' },
  { slug: 'bacon', displayName: 'Francis Bacon' },
  { slug: 'galile', displayName: 'Galileo Galilei' },
  { slug: 'descar', displayName: 'René Descartes' },
  { slug: 'spinoz', displayName: 'Baruch Spinoza' },
  { slug: 'leibni', displayName: 'Gottfried Leibniz' },
  { slug: 'locke', displayName: 'John Locke' },
  { slug: 'berkel', displayName: 'George Berkeley' },
  { slug: 'humes', displayName: 'David Hume' },
  { slug: 'kants', displayName: 'Immanuel Kant' },
  { slug: 'rousse', displayName: 'Jean-Jacques Rousseau' },
  { slug: 'volta', displayName: 'Voltaire' },
  { slug: 'didero', displayName: 'Denis Diderot' },
  { slug: 'condil', displayName: 'Condillac' },
  { slug: 'helvet', displayName: 'Helvetius' },
  { slug: 'hobbes', displayName: 'Thomas Hobbes' },
  { slug: 'gassend', displayName: 'Pierre Gassendi' },
  { slug: 'malebr', displayName: 'Malebranche' },
  { slug: 'pascal', displayName: 'Blaise Pascal' },
  { slug: 'bayle', displayName: 'Pierre Bayle' },
  { slug: 'montes', displayName: 'Montesquieu' },
  { slug: 'kantor', displayName: 'Immanuel Kant' },
  { slug: 'fichte', displayName: 'Johann Fichte' },
  { slug: 'schell', displayName: 'Friedrich Schelling' },
  { slug: 'hegel', displayName: 'Georg Hegel' },
  { slug: 'schope', displayName: 'Arthur Schopenhauer' },
  { slug: 'kierke', displayName: 'Søren Kierkegaard' },
  { slug: 'marxis', displayName: 'Karl Marx' },
  { slug: 'engels', displayName: 'Friedrich Engels' },
  { slug: 'nietzs', displayName: 'Friedrich Nietzsche' },
  { slug: 'dilthe', displayName: 'Wilhelm Dilthey' },
  { slug: 'husser', displayName: 'Edmund Husserl' },
  { slug: 'heideg', displayName: 'Martin Heidegger' },
  { slug: 'sartre', displayName: 'Jean-Paul Sartre' },
  { slug: 'camus', displayName: 'Albert Camus' },
  { slug: 'beauvo', displayName: 'Simone de Beauvoir' },
  { slug: 'merlea', displayName: 'Maurice Merleau-Ponty' },
  { slug: 'levina', displayName: 'Emmanuel Levinas' },
  { slug: 'derrid', displayName: 'Jacques Derrida' },
  { slug: 'foucau', displayName: 'Michel Foucault' },
  { slug: 'deleuz', displayName: 'Gilles Deleuze' },
  { slug: 'guatta', displayName: 'Félix Guattari' },
  { slug: 'lyotar', displayName: 'Jean-François Lyotard' },
  { slug: 'baudri', displayName: 'Jean Baudrillard' },
  { slug: 'haberm', displayName: 'Jürgen Habermas' },
  { slug: 'popper', displayName: 'Karl Popper' },
  { slug: 'wittge', displayName: 'Ludwig Wittgenstein' },
  { slug: 'moore', displayName: 'G. E. Moore' },
  { slug: 'frege', displayName: 'Gottlob Frege' },
  { slug: 'carnap', displayName: 'Rudolf Carnap' },
  { slug: 'quine', displayName: 'Willard Quine' },
  { slug: 'david', displayName: 'Donald Davidson' },
  { slug: 'rawls', displayName: 'John Rawls' },
  { slug: 'nozick', displayName: 'Robert Nozick' },
  { slug: 'parfit', displayName: 'Derek Parfit' },
  { slug: 'singer', displayName: 'Peter Singer' },
  { slug: 'macint', displayName: 'Alasdair MacIntyre' },
  { slug: 'taylor', displayName: 'Charles Taylor' },
  { slug: 'ricoeu', displayName: 'Paul Ricoeur' },
  { slug: 'gadame', displayName: 'Hans-Georg Gadamer' },
  { slug: 'benjam', displayName: 'Walter Benjamin' },
  { slug: 'adorno', displayName: 'Theodor Adorno' },
  { slug: 'horkhe', displayName: 'Max Horkheimer' },
  { slug: 'althus', displayName: 'Louis Althusser' },
  { slug: 'gramsc', displayName: 'Antonio Gramsci' },
  { slug: 'lukacs', displayName: 'György Lukács' },
  { slug: 'bennet', displayName: 'Jonathan Bennett' },
  { slug: 'straw', displayName: 'P. F. Strawson' },
  { slug: 'anscom', displayName: 'G. E. M. Anscombe' },
  { slug: 'willia', displayName: 'Bernard Williams' },
  { slug: 'mackie', displayName: 'J. L. Mackie' },
  { slug: 'kripke', displayName: 'Saul Kripke' },
  { slug: 'putnam', displayName: 'Hilary Putnam' },
  { slug: 'rorty', displayName: 'Richard Rorty' },
  { slug: 'dennet', displayName: 'Daniel Dennett' },
  { slug: 'chalm', displayName: 'David Chalmers' },
  { slug: 'searle', displayName: 'John Searle' },
  { slug: 'nagel', displayName: 'Thomas Nagel' },
  { slug: 'fodor', displayName: 'Jerry Fodor' },
  { slug: 'block', displayName: 'Ned Block' },
  { slug: 'lewis', displayName: 'David Lewis' },
  { slug: 'armstr', displayName: 'D. M. Armstrong' },
  { slug: 'gettie', displayName: 'Edmund Gettier' },
  { slug: 'goldma', displayName: 'Alvin Goldman' },
  { slug: 'planti', displayName: 'Alvin Plantinga' },
  { slug: 'swinbu', displayName: 'Richard Swinburne' },
  { slug: 'philli', displayName: 'D. Z. Phillips' },
  { slug: 'wisdom', displayName: 'John Wisdom' },
  { slug: 'reichen', displayName: 'Hans Reichenbach' },
  { slug: 'schlick', displayName: 'Moritz Schlick' },
  { slug: 'neurath', displayName: 'Otto Neurath' },
  { slug: 'peirce', displayName: 'Charles Peirce' },
  { slug: 'james', displayName: 'William James' },
  { slug: 'dewey', displayName: 'John Dewey' },
  { slug: 'santay', displayName: 'George Santayana' },
  { slug: 'whiteh', displayName: 'Alfred North Whitehead' },
  { slug: 'bradle', displayName: 'F. H. Bradley' },
  { slug: 'green', displayName: 'T. H. Green' },
  { slug: 'bosanq', displayName: 'Bernard Bosanquet' },
  { slug: 'croce', displayName: 'Benedetto Croce' },
  { slug: 'gentil', displayName: 'Giovanni Gentile' },
  { slug: 'confuc', displayName: 'Confucius' },
  { slug: 'laotzu', displayName: 'Laozi' },
  { slug: 'menciu', displayName: 'Mencius' },
  { slug: 'xunzi', displayName: 'Xunzi' },
  { slug: 'zhuang', displayName: 'Zhuangzi' },
  { slug: 'hanfei', displayName: 'Han Fei' },
  { slug: 'dongzh', displayName: 'Dong Zhongshu' },
  { slug: 'zhuxi', displayName: 'Zhu Xi' },
  { slug: 'wangya', displayName: 'Wang Yangming' },
  { slug: 'shankar', displayName: 'Adi Shankara' },
  { slug: 'ramanu', displayName: 'Ramanuja' },
  { slug: 'madhva', displayName: 'Madhva' },
  { slug: 'nagarj', displayName: 'Nagarjuna' },
  { slug: 'asanga', displayName: 'Asanga' },
  { slug: 'vasuba', displayName: 'Vasubandhu' },
  { slug: 'dharma', displayName: 'Dharmakirti' },
  { slug: 'buddha', displayName: 'Buddha' },
  { slug: 'bodhid', displayName: 'Bodhidharma' },
  { slug: 'dogen', displayName: 'Dogen' },
  { slug: 'nichir', displayName: 'Nichiren' },
  { slug: 'honen', displayName: 'Honen' },
  { slug: 'shinran', displayName: 'Shinran' },
  { slug: 'alghaz', displayName: 'Al-Ghazali' },
  { slug: 'ibnsin', displayName: 'Ibn Sina' },
  { slug: 'ibnrus', displayName: 'Ibn Rushd' },
  { slug: 'ibntuf', displayName: 'Ibn Tufayl' },
  { slug: 'ibnarb', displayName: 'Ibn Arabi' },
  { slug: 'alkind', displayName: 'Al-Kindi' },
  { slug: 'alfara', displayName: 'Al-Farabi' },
  { slug: 'ibnkha', displayName: 'Ibn Khaldun' },
  { slug: 'alrazi', displayName: 'Al-Razi' },
  { slug: 'suhraw', displayName: 'Al-Suhrawardi' },
  { slug: 'ibntay', displayName: 'Ibn Taymiyyah' },
  { slug: 'alashar', displayName: 'Al-Ashari' },
  { slug: 'mutaza', displayName: 'Al-Mutazila' },
  { slug: 'jafari', displayName: 'Ja far al-Sadiq' },
  { slug: 'schlei', displayName: 'Friedrich Schleiermacher' },
  { slug: 'herder', displayName: 'Johann Herder' },
  { slug: 'lessin', displayName: 'Gotthold Lessing' },
  { slug: 'jacobi', displayName: 'Friedrich Jacobi' },
  { slug: 'romano', displayName: 'Giordano Bruno' },
  { slug: 'copern', displayName: 'Nicolaus Copernicus' },
  { slug: 'kepler', displayName: 'Johannes Kepler' },
  { slug: 'newton', displayName: 'Isaac Newton' },
  { slug: 'huygen', displayName: 'Christiaan Huygens' },
  { slug: 'priest', displayName: 'Joseph Priestley' },
  { slug: 'price', displayName: 'Richard Price' },
  { slug: 'fergus', displayName: 'Adam Ferguson' },
  { slug: 'smith', displayName: 'Adam Smith' },
  { slug: 'mendel', displayName: 'Moses Mendelssohn' },
  { slug: 'comte', displayName: 'Auguste Comte' },
  { slug: 'bentha', displayName: 'Jeremy Bentham' },
  { slug: 'sidgwi', displayName: 'Henry Sidgwick' },
  { slug: 'spence', displayName: 'Herbert Spencer' },
  { slug: 'royce', displayName: 'Josiah Royce' },
  { slug: 'cooley', displayName: 'Charles Cooley' },
  { slug: 'durkhe', displayName: 'Émile Durkheim' },
  { slug: 'weber', displayName: 'Max Weber' },
  { slug: 'simmel', displayName: 'Georg Simmel' },
  { slug: 'pareto', displayName: 'Vilfredo Pareto' },
  { slug: 'mosca', displayName: 'Gaetano Mosca' },
  { slug: 'luxemb', displayName: 'Rosa Luxemburg' },
  { slug: 'lenin', displayName: 'Vladimir Lenin' },
  { slug: 'trotsk', displayName: 'Leon Trotsky' },
  { slug: 'fromm', displayName: 'Erich Fromm' },
  { slug: 'arendt', displayName: 'Hannah Arendt' },
  { slug: 'hayek', displayName: 'Friedrich Hayek' },
  { slug: 'mises', displayName: 'Ludwig von Mises' },
  { slug: 'dworki', displayName: 'Ronald Dworkin' },
  { slug: 'austin', displayName: 'J. L. Austin' },
  { slug: 'grice', displayName: 'H. P. Grice' },
  { slug: 'goodma', displayName: 'Nelson Goodman' },
  { slug: 'sellars', displayName: 'Wilfrid Sellars' },
  { slug: 'smart', displayName: 'J. J. C. Smart' },
  { slug: 'place', displayName: 'U. T. Place' },
  { slug: 'feigl', displayName: 'Herbert Feigl' },
  { slug: 'flanag', displayName: 'Owen Flanagan' },
  { slug: 'church', displayName: 'Patricia Churchland' },
  { slug: 'vanfra', displayName: 'Bas van Fraassen' },
  { slug: 'laudan', displayName: 'Larry Laudan' },
  { slug: 'feyer', displayName: 'Paul Feyerabend' },
  { slug: 'lakato', displayName: 'Imre Lakatos' },
  { slug: 'russell', displayName: 'Bertrand Russell' },
  { slug: 'butler', displayName: 'Judith Butler' },
  { slug: 'irigar', displayName: 'Luce Irigaray' },
  { slug: 'kriste', displayName: 'Julia Kristeva' },
  { slug: 'cixous', displayName: 'Hélène Cixous' },
  { slug: 'spivak', displayName: 'Gayatri Spivak' },
  { slug: 'fanon', displayName: 'Frantz Fanon' },
  { slug: 'cesair', displayName: 'Aimé Césaire' },
  { slug: 'sengh', displayName: 'Léopold Senghor' },
  { slug: 'ngugi', displayName: 'Ngũgĩ wa Thiong o' },
  { slug: 'wiredu', displayName: 'Kwasi Wiredu' },
  { slug: 'hounto', displayName: 'Paulin Hountondji' },
  { slug: 'appiah', displayName: 'Kwame Anthony Appiah' },
  { slug: 'coates', displayName: 'Ta-Nehisi Coates' },
  { slug: 'hooks', displayName: 'bell hooks' },
  { slug: 'collins', displayName: 'Patricia Hill Collins' },
  { slug: 'lorde', displayName: 'Audre Lorde' },
  { slug: 'wollst', displayName: 'Mary Wollstonecraft' },
  { slug: 'simone', displayName: 'Simone Weil' },
  { slug: 'stein', displayName: 'Edith Stein' },
  { slug: 'nussba', displayName: 'Martha Nussbaum' },
  { slug: 'young', displayName: 'Iris Marion Young' },
  { slug: 'benhab', displayName: 'Seyla Benhabib' },
  { slug: 'fraser', displayName: 'Nancy Fraser' },
  { slug: 'haraway', displayName: 'Donna Haraway' },
  { slug: 'hardin', displayName: 'Garrett Hardin' },
  { slug: 'scanlo', displayName: 'T. M. Scanlon' },
  { slug: 'mavrod', displayName: 'John Mavrodes' },
  { slug: 'adams', displayName: 'Robert Merrihew Adams' },
  { slug: 'vaninw', displayName: 'Peter van Inwagen' },
  { slug: 'xenoph', displayName: 'Xenophanes' },
  { slug: 'meliss', displayName: 'Melissus' },
  { slug: 'leucip', displayName: 'Leucippus' },
  { slug: 'dubois', displayName: 'W. E. B. Du Bois' },
  { slug: 'depiz', displayName: 'Christine de Pizan' },
  { slug: 'philo', displayName: 'Philo of Alexandria' },
  { slug: 'origen', displayName: 'Origen' },
  { slug: 'tertul', displayName: 'Tertullian' },
  { slug: 'clemen', displayName: 'Clement of Alexandria' },
  { slug: 'basili', displayName: 'Basil of Caesarea' },
  { slug: 'gregor', displayName: 'Gregory of Nyssa' },
  { slug: 'johnch', displayName: 'John Chrysostom' },
  { slug: 'jerome', displayName: 'Jerome' },
  { slug: 'isidor', displayName: 'Isidore of Seville' },
  { slug: 'alcuin', displayName: 'Alcuin' },
  { slug: 'petrard', displayName: 'Petrarch' },
  { slug: 'boccac', displayName: 'Boccaccio' },
  { slug: 'machia', displayName: 'Machiavelli' },
  { slug: 'zwingl', displayName: 'Zwingli' },
  { slug: 'melanc', displayName: 'Melanchthon' },
  { slug: 'servet', displayName: 'Servetus' },
  { slug: 'bruno', displayName: 'Giordano Bruno' },
  { slug: 'teles', displayName: 'Telesio' },
  { slug: 'campan', displayName: 'Campanella' },
  { slug: 'vanini', displayName: 'Vanini' },
  { slug: 'grotiu', displayName: 'Grotius' },
  { slug: 'selden', displayName: 'Selden' },
  { slug: 'harrin', displayName: 'Harrington' },
  { slug: 'filmer', displayName: 'Filmer' },
  { slug: 'cudwor', displayName: 'Cudworth' },
  { slug: 'moreh', displayName: 'Henry More' },
  { slug: 'norris', displayName: 'Norris' },
  { slug: 'berke', displayName: 'Berkeley' },
  { slug: 'hutche', displayName: 'Hutcheson' },
  { slug: 'feuerb', displayName: 'Feuerbach' },
  { slug: 'lassal', displayName: 'Lassalle' },
  { slug: 'bakuni', displayName: 'Bakunin' },
  { slug: 'kropot', displayName: 'Kropotkin' },
  { slug: 'plekha', displayName: 'Plekhanov' },
  { slug: 'sextus', displayName: 'Sextus Empiricus' },
  { slug: 'carnea', displayName: 'Carneades' },
  { slug: 'arcesi', displayName: 'Arcesilaus' },
  { slug: 'antio', displayName: 'Antiochus' },
  { slug: 'panait', displayName: 'Panaetius' },
  { slug: 'posido', displayName: 'Posidonius' },
  { slug: 'philop', displayName: 'Philoponus' },
  { slug: 'damasc', displayName: 'Damascius' },
  { slug: 'johnph', displayName: 'John Philoponus' },
  { slug: 'olymp', displayName: 'Olympiodorus' },
  { slug: 'themis', displayName: 'Themistius' },
  { slug: 'syrian', displayName: 'Syrianus' },
  { slug: 'asclep', displayName: 'Asclepius of Tralles' },
  { slug: 'johnsc', displayName: 'John Scotus Eriugena' },
  { slug: 'petera', displayName: 'Peter Abelard' },
  { slug: 'bernar', displayName: 'Bernard of Clairvaux' },
  { slug: 'thomas', displayName: 'Thomas Aquinas' },
  { slug: 'cohen', displayName: 'G. A. Cohen' },
  { slug: 'walzer', displayName: 'Michael Walzer' },
  { slug: 'sorabj', displayName: 'Richard Sorabji' },
  { slug: 'annas', displayName: 'Julia Annas' },
  { slug: 'cooper', displayName: 'John M. Cooper' },
  { slug: 'irwin', displayName: 'Terence Irwin' },
  { slug: 'barnes', displayName: 'Jonathan Barnes' },
  { slug: 'guthr', displayName: 'W. K. C. Guthrie' },
  { slug: 'vlasto', displayName: 'Gregory Vlastos' },
  { slug: 'burnye', displayName: 'Myles Burnyeat' },
  { slug: 'mckenz', displayName: 'Angus McKenzie' },
  { slug: 'sedley', displayName: 'David Sedley' },
  { slug: 'schofi', displayName: 'Malcolm Schofield' },
  { slug: 'grote', displayName: 'George Grote' },
  { slug: 'grotes', displayName: 'George Grote' },
] as const;

export const PHILOSOPHER_SLUGS = new Set(PHILOSOPHER_CATALOG.map((p) => p.slug));

export function isPhilosopherSlug(slug: string): boolean {
  return PHILOSOPHER_SLUGS.has(slug);
}

export function getPhilosopherBySlug(slug: string): Philosopher | undefined {
  return PHILOSOPHER_CATALOG.find((p) => p.slug === slug);
}
