/** Wikipedia portrait URLs keyed by philosopher slug. */
export const PHILOSOPHER_PORTRAITS: Record<string, string> = {
  plato:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Plato_Silanion_Musei_Capitolini_MC1377.png/330px-Plato_Silanion_Musei_Capitolini_MC1377.png',
  socrat:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Socrates_Louvre.jpg/330px-Socrates_Louvre.jpg',
  aristo:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Aristotle_Altemps_Inv8575.jpg/330px-Aristotle_Altemps_Inv8575.jpg',
  thales:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Illustrerad_Verldshistoria_band_I_Ill_107.jpg/330px-Illustrerad_Verldshistoria_band_I_Ill_107.jpg',
  anaxim:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Pietro_Bellotti_%28attr%29_Anaximander.jpg/330px-Pietro_Bellotti_%28attr%29_Anaximander.jpg',
  anaxag:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Anaxagoras_Lebiedzki_Rahl.jpg/330px-Anaxagoras_Lebiedzki_Rahl.jpg',
  heracl:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Heraclitus_b_4_compressed.jpg/330px-Heraclitus_b_4_compressed.jpg',
  parmen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Busto_di_Parmenide_%28cropped%29.jpg/330px-Busto_di_Parmenide_%28cropped%29.jpg',
  empedo:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Empedokles.jpeg/330px-Empedokles.jpeg',
  democr:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Unknown_greek_pushkin.jpg/330px-Unknown_greek_pushkin.jpg',
  protag:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Ribera_-_Protagoras%2C_1637.jpg/330px-Ribera_-_Protagoras%2C_1637.jpg',
  gorgia:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Gorgia_di_Leontini.png/330px-Gorgia_di_Leontini.png',
  prodic:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/CarracciHercules.jpg/330px-CarracciHercules.jpg',
  antist:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Antisthenes_Pio-Clementino_Inv288.jpg/330px-Antisthenes_Pio-Clementino_Inv288.jpg',
  diogen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Diogenes_Mosaic_R%C3%B6misch-Germanisches_Museum.jpg/330px-Diogenes_Mosaic_R%C3%B6misch-Germanisches_Museum.jpg',
  crates:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Crates_of_Thebes_Villa_Farnesina.jpg/330px-Crates_of_Thebes_Villa_Farnesina.jpg',
  zenodo:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Paolo_Monti_-_Servizio_fotografico_%28Napoli%2C_1969%29_-_BEIC_6353768.jpg/330px-Paolo_Monti_-_Servizio_fotografico_%28Napoli%2C_1969%29_-_BEIC_6353768.jpg',
  cleant:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cleanthes_from_L._Annaei_Senecae_philosophi_Opera%2C_1605%2C_title_page_detail.png/330px-Cleanthes_from_L._Annaei_Senecae_philosophi_Opera%2C_1605%2C_title_page_detail.png',
  chrysi:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chrysippos_BM_1846.jpg/330px-Chrysippos_BM_1846.jpg',
  epicur:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Epikouros_BM_1843.jpg/330px-Epikouros_BM_1843.jpg',
  lucret:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lucretius_pointing_to_the_casus.jpg/330px-Lucretius_pointing_to_the_casus.jpg',
  cicero:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Bust_of_Cicero_%281st-cent._BC%29_-_Palazzo_Nuovo_-_Musei_Capitolini_-_Rome_2016.jpg/330px-Bust_of_Cicero_%281st-cent._BC%29_-_Palazzo_Nuovo_-_Musei_Capitolini_-_Rome_2016.jpg',
  epictet:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Epicteti_Enchiridion_Latinis_versibus_adumbratum_%28Oxford_1715%29_frontispiece_%28cropped%29.jpg/330px-Epicteti_Enchiridion_Latinis_versibus_adumbratum_%28Oxford_1715%29_frontispiece_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  marcus:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/MSR-ra-61-b-1-DM.jpg/330px-MSR-ra-61-b-1-DM.jpg',
  plotin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Plotinos.jpg/330px-Plotinos.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  iambli: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Iamblichus.jpg',
  procli:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/In_primum_Euclidis_elementorum_librum_01.jpg/330px-In_primum_Euclidis_elementorum_librum_01.jpg',
  boethi:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Boethius.jpeg/330px-Boethius.jpeg',
  august:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Saint_Augustine_by_Philippe_de_Champaigne.jpg/330px-Saint_Augustine_by_Philippe_de_Champaigne.jpg',
  anselm:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Anselm_of_Canterbury%2C_seal.svg/330px-Anselm_of_Canterbury%2C_seal.svg.png',
  abelar:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Piotr_Abelard_%28cropped%29.jpg/330px-Piotr_Abelard_%28cropped%29.jpg',
  avice:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Avicenna_Bust%2C_left_profile_%28cropped%29.jpg/330px-Avicenna_Bust%2C_left_profile_%28cropped%29.jpg',
  averro:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Andrea_di_bonaiuto%2C_apotesosi_di_san_tommaso_d%27aquino%2C_11_averro%C3%A8.jpg/330px-Andrea_di_bonaiuto%2C_apotesosi_di_san_tommaso_d%27aquino%2C_11_averro%C3%A8.jpg',
  maimon:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Portrait_of_Moses_Maimonides_in_Thesaurus_antiquitatum_sacrarum.tif/lossy-page1-330px-Portrait_of_Moses_Maimonides_in_Thesaurus_antiquitatum_sacrarum.tif.jpg',
  albert:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Vicente_salvador_gomez-san_alberto.jpg/330px-Vicente_salvador_gomez-san_alberto.jpg',
  aquina:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/St-thomas-aquinasFXD.jpg/330px-St-thomas-aquinasFXD.jpg',
  bonave:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Fran%C3%A7ois%2C_Claude_%28dit_Fr%C3%A8re_Luc%29_-_Saint_Bonaventure.jpg/330px-Fran%C3%A7ois%2C_Claude_%28dit_Fr%C3%A8re_Luc%29_-_Saint_Bonaventure.jpg',
  ockham: 'https://upload.wikimedia.org/wikipedia/commons/7/70/William_of_Ockham.png',
  wyclif:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Wycliffe_by_Kirby.jpg/330px-Wycliffe_by_Kirby.jpg',
  erasmu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Holbein-erasmus.jpg/330px-Holbein-erasmus.jpg',
  luther:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg/330px-Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  calvin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/John_Calvin_Museum_Catharijneconvent_RMCC_s84_cropped.png/330px-John_Calvin_Museum_Catharijneconvent_RMCC_s84_cropped.png',
  bacon:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Somer_Francis_Bacon.jpg/330px-Somer_Francis_Bacon.jpg',
  galile:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff/lossy-page1-330px-Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff.jpg',
  descar:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg/330px-Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg',
  spinoz: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Spinoza.jpg/330px-Spinoza.jpg',
  leibni:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Christoph_Bernhard_Francke_-_Bildnis_des_Philosophen_Leibniz_%28ca._1695%29.jpg/330px-Christoph_Bernhard_Francke_-_Bildnis_des_Philosophen_Leibniz_%28ca._1695%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  locke:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Godfrey_Kneller_-_Portrait_of_John_Locke_%28Hermitage%29.jpg/330px-Godfrey_Kneller_-_Portrait_of_John_Locke_%28Hermitage%29.jpg',
  berkel:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/George_Berkeley_by_John_Smibert.jpg/330px-George_Berkeley_by_John_Smibert.jpg',
  humes:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/David_Hume_Ramsay.jpg/330px-David_Hume_Ramsay.jpg',
  kants:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Immanuel_Kant_-_Gemaelde_1.jpg/330px-Immanuel_Kant_-_Gemaelde_1.jpg',
  rousse:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Maurice_Quentin_de_La_Tour_-_Portrait_of_Jean-Jacques_Rousseau_-_adjusted.jpg/330px-Maurice_Quentin_de_La_Tour_-_Portrait_of_Jean-Jacques_Rousseau_-_adjusted.jpg',
  volta:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Nicolas_de_Largilli%C3%A8re_-_Portrait_de_Voltaire_%281694-1778%29_en_1718_-_P208_-_mus%C3%A9e_Carnavalet_-_5_%28cropped%29.jpg/330px-Nicolas_de_Largilli%C3%A8re_-_Portrait_de_Voltaire_%281694-1778%29_en_1718_-_P208_-_mus%C3%A9e_Carnavalet_-_5_%28cropped%29.jpg',
  didero:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Denis_Diderot_by_Louis-Michel_van_Loo.jpg/330px-Denis_Diderot_by_Louis-Michel_van_Loo.jpg',
  hobbes:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Thomas_Hobbes_by_John_Michael_Wright_%28colour%29_%283x4_cropped%29.jpg/330px-Thomas_Hobbes_by_John_Michael_Wright_%28colour%29_%283x4_cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  gassend:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/PierreGassendi.jpg/330px-PierreGassendi.jpg',
  pascal:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Blaise_Pascal_Versailles.JPG/330px-Blaise_Pascal_Versailles.JPG',
  bayle:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Pierre_Bayle_by_Louis_Ferdinand_Elle.jpg/330px-Pierre_Bayle_by_Louis_Ferdinand_Elle.jpg',
  montes:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Charles_Montesquieu.jpg/330px-Charles_Montesquieu.jpg',
  kantor:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Immanuel_Kant_-_Gemaelde_1.jpg/330px-Immanuel_Kant_-_Gemaelde_1.jpg',
  fichte:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Johann_Gottlieb_Fichte.jpg/330px-Johann_Gottlieb_Fichte.jpg',
  schell:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Nb_pinacoteca_stieler_friedrich_wilhelm_joseph_von_schelling.jpg/330px-Nb_pinacoteca_stieler_friedrich_wilhelm_joseph_von_schelling.jpg',
  hegel:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Jakob_Schlesinger_-_Hegel_1831.jpg/330px-Jakob_Schlesinger_-_Hegel_1831.jpg',
  schope:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Arthur_Schopenhauer_by_J_Sch%C3%A4fer%2C_1859b.jpg/330px-Arthur_Schopenhauer_by_J_Sch%C3%A4fer%2C_1859b.jpg',
  kierke:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/S%C3%B8ren_Kierkegaard_%281813-1855%29_-_%28cropped%29.jpg/330px-S%C3%B8ren_Kierkegaard_%281813-1855%29_-_%28cropped%29.jpg',
  marxis:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Karl_Marx_by_John_Jabez_Edwin_Mayall_1875_-_Restored_%26_Adjusted_%283x4_cropped_b%29.png/330px-Karl_Marx_by_John_Jabez_Edwin_Mayall_1875_-_Restored_%26_Adjusted_%283x4_cropped_b%29.png',
  engels:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Friedrich_Engels_portrait_%28cropped%29.jpg/330px-Friedrich_Engels_portrait_%28cropped%29.jpg',
  nietzs:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/330px-Nietzsche187a.jpg',
  dilthe:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Portrait_Dilthey.jpg/330px-Portrait_Dilthey.jpg',
  husser:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Edmund_Husserl_1910s.jpg/330px-Edmund_Husserl_1910s.jpg',
  heideg:
    'https://upload.wikimedia.org/wikipedia/commons/1/12/Freiburg%2C_Z%C3%A4hringen-_Jahnhalle%2C_Prof._Martin_Heidegger_w%C3%A4hrend_eines_Vortrags_-_LABW_-_Staatsarchiv_Freiburg_W_134_Nr._023740f_%28cropped%29.jpeg',
  sartre:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Jean_Paul_Sartre_1965.jpg/330px-Jean_Paul_Sartre_1965.jpg',
  camus:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Albert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg/330px-Albert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg',
  beauvo:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Simone_De_Beauvoir_%28cropped%29.jpg/330px-Simone_De_Beauvoir_%28cropped%29.jpg',
  merlea:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Maurice_Merleau-Ponty.jpg/330px-Maurice_Merleau-Ponty.jpg',
  levina:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Emmanuel_Levinas.jpg/330px-Emmanuel_Levinas.jpg',
  derrid:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Derrida_EHESS_%28cropped%29.png/330px-Derrida_EHESS_%28cropped%29.png',
  foucau:
    'https://upload.wikimedia.org/wikipedia/commons/c/ca/Photo_of_Michel_Foucault_on_1970_dustjacket_of_The_Order_of_Things.jpg',
  deleuz: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Gilles_Deleuze.webp',
  guatta:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/%E3%83%95%E3%82%A7%E3%83%AA%E3%83%83%E3%82%AF%E3%82%B9%E3%83%BB%E3%82%AC%E3%82%BF%E3%83%AA.jpg/330px-%E3%83%95%E3%82%A7%E3%83%AA%E3%83%83%E3%82%AF%E3%82%B9%E3%83%BB%E3%82%AC%E3%82%BF%E3%83%AA.jpg',
  lyotar:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Jean-Francois_Lyotard_cropped.jpg/330px-Jean-Francois_Lyotard_cropped.jpg',
  baudri:
    'https://upload.wikimedia.org/wikipedia/commons/e/ef/WikipediaBaudrillard20040612-cropped.png',
  haberm:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/JuergenHabermas_crop1.jpg/330px-JuergenHabermas_crop1.jpg',
  popper:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Karl_Popper.jpg/330px-Karl_Popper.jpg',
  wittge:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ludwig_Wittgenstein_1929.jpg/330px-Ludwig_Wittgenstein_1929.jpg',
  moore:
    'https://upload.wikimedia.org/wikipedia/commons/b/b9/1914_George_Edward_Moore_%28cropped%29.jpg',
  frege:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Young_frege.jpg/330px-Young_frege.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  carnap:
    'https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Rudolf_Carnap_1930.jpeg/330px-Rudolf_Carnap_1930.jpeg',
  quine:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Willard_Van_Orman_Quine_on_Bluenose_II_in_Halifax_NS_harbor_1980.jpg/330px-Willard_Van_Orman_Quine_on_Bluenose_II_in_Halifax_NS_harbor_1980.jpg',
  rawls:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/John_Rawls_%281971_photo_portrait%29.jpg/330px-John_Rawls_%281971_photo_portrait%29.jpg',
  nozick:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Robert_Nozick_1977_Libertarian_Review_cover_%284x5_cropped%29.jpg/330px-Robert_Nozick_1977_Libertarian_Review_cover_%284x5_cropped%29.jpg',
  parfit:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Derek_Parfit_at_Harvard-April_21%2C_2015-Effective_Altruism_%28cropped%29.jpg/330px-Derek_Parfit_at_Harvard-April_21%2C_2015-Effective_Altruism_%28cropped%29.jpg',
  singer:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Peter_Singer_2017_%28cropped%29.jpg/330px-Peter_Singer_2017_%28cropped%29.jpg',
  macint:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Alasdair_MacIntyre.jpg/330px-Alasdair_MacIntyre.jpg',
  taylor:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Charlemagne_and_Pope_Adrian_I.jpg/330px-Charlemagne_and_Pope_Adrian_I.jpg',
  ricoeu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Paul_Ricoeur_Balzan.png/330px-Paul_Ricoeur_Balzan.png',
  gadame:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Hans-Georg_Gadamer.jpg/330px-Hans-Georg_Gadamer.jpg',
  benjam:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Benjamin_%28after_Francisco_de_Zurbar%C3%A1n%29.jpg/330px-Benjamin_%28after_Francisco_de_Zurbar%C3%A1n%29.jpg',
  adorno:
    'https://upload.wikimedia.org/wikipedia/commons/1/18/Theodor_W._Adorno.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled',
  horkhe: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Max_Horkheimer.jpg',
  althus: 'https://upload.wikimedia.org/wikipedia/en/5/51/Althusser.jpg',
  gramsc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Gramsci.png/330px-Gramsci.png',
  lukacs:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Luk%C3%A1cs_Gy%C3%B6rgy.jpg/330px-Luk%C3%A1cs_Gy%C3%B6rgy.jpg',
  straw: 'https://upload.wikimedia.org/wikipedia/en/7/76/P._F._Strawson.jpg',
  anscom: 'https://upload.wikimedia.org/wikipedia/en/0/02/Gertrude_Elizabeth_Margaret_Anscombe.jpg',
  willia: 'https://upload.wikimedia.org/wikipedia/en/a/a6/BernardWilliams.jpg',
  mackie: 'https://upload.wikimedia.org/wikipedia/en/7/76/John_Leslie_Mackie.jpg',
  kripke:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Saul_1878.jpg/330px-Saul_1878.jpg',
  putnam:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Hilary_Putnam.jpg/330px-Hilary_Putnam.jpg',
  rorty:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Una_foto_en_la_ventana_de_Rorty_en_Barcelona.jpg/330px-Una_foto_en_la_ventana_de_Rorty_en_Barcelona.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  dennet:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Daniel_Dennett_2.jpg/330px-Daniel_Dennett_2.jpg',
  chalm:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/David_chalmers.jpg/330px-David_chalmers.jpg',
  searle:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/John_searle2.jpg/330px-John_searle2.jpg',
  nagel:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Thomas_Nagel_%28cropped%29.jpg/330px-Thomas_Nagel_%28cropped%29.jpg',
  fodor:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Jerry_Fodor.jpg/330px-Jerry_Fodor.jpg',
  block: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Large_ned.block.jpg',
  lewis:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/King_David%2C_the_King_of_Israel.jpg/330px-King_David%2C_the_King_of_Israel.jpg',
  armstr:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/DavidMArmstrong.jpg/330px-DavidMArmstrong.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  gettie:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Edmund_L_Gettier_III_ca_1960s_umass.jpg/330px-Edmund_L_Gettier_III_ca_1960s_umass.jpg',
  goldma:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Alvin_Goldman_1966.jpg/330px-Alvin_Goldman_1966.jpg',
  planti:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Alvin_Plantinga.jpg/330px-Alvin_Plantinga.jpg',
  swinbu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Richard_Swinburne.jpg/330px-Richard_Swinburne.jpg',
  philli: 'https://upload.wikimedia.org/wikipedia/en/1/11/Dewi_Zephaniah_Phillips.jpg',
  wisdom:
    'https://upload.wikimedia.org/wikipedia/en/3/3c/Philosopher_John_Wisdom_%281904_%E2%80%93_1993%29.jpg',
  reichen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/H_Reichenbach.jpg/330px-H_Reichenbach.jpg',
  schlick:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Schlick_sitting.jpg/330px-Schlick_sitting.jpg',
  neurath:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Otto%2Bvon%2Bbismarck.jpg/330px-Otto%2Bvon%2Bbismarck.jpg',
  peirce:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Charles_Sanders_Peirce.png/330px-Charles_Sanders_Peirce.png',
  james:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/William_James_b1842c.jpg/330px-William_James_b1842c.jpg',
  dewey:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/John_Dewey_cph.3a51565.jpg/330px-John_Dewey_cph.3a51565.jpg',
  santay:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/George_Santayana.jpg/330px-George_Santayana.jpg',
  whiteh:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/ANWhitehead.jpg/330px-ANWhitehead.jpg',
  bradle:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/F.H._Bradley.png/330px-F.H._Bradley.png',
  green:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/T.H._Green.png/330px-T.H._Green.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  bosanq:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Stained_glass_St_Bernard_MNMA_Cl3273.jpg/330px-Stained_glass_St_Bernard_MNMA_Cl3273.jpg',
  croce:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Benedetto_Croce_01.jpg/330px-Benedetto_Croce_01.jpg',
  gentil:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Giovanni_Gentile_sgr.jpg/330px-Giovanni_Gentile_sgr.jpg',
  confuc:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Confucius_Tang_Dynasty.jpg/330px-Confucius_Tang_Dynasty.jpg',
  laotzu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Laozi_%28Chinese_characters%29.svg/330px-Laozi_%28Chinese_characters%29.svg.png',
  menciu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Half_Portraits_of_the_Great_Sage_and_Virtuous_Men_of_Old_-_Meng_Ke_%28%E5%AD%9F%E8%BB%BB%29.jpg/330px-Half_Portraits_of_the_Great_Sage_and_Virtuous_Men_of_Old_-_Meng_Ke_%28%E5%AD%9F%E8%BB%BB%29.jpg',
  hanfei:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Statue_Of_Han_Fei.png/330px-Statue_Of_Han_Fei.png',
  dongzh:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/%E6%AD%B7%E4%BB%A3%E8%81%96%E8%B3%A2%E5%8D%8A%E8%BA%AB%E5%83%8F_%E5%86%8A_%E8%91%A3%E4%BB%B2%E8%88%92_%28Dong_Zhongshu%29.png/330px-%E6%AD%B7%E4%BB%A3%E8%81%96%E8%B3%A2%E5%8D%8A%E8%BA%AB%E5%83%8F_%E5%86%8A_%E8%91%A3%E4%BB%B2%E8%88%92_%28Dong_Zhongshu%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  zhuxi: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Zhu_xi.jpg/330px-Zhu_xi.jpg',
  wangya:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/%E7%8E%8B%E5%AE%88%E4%BB%81.jpg/330px-%E7%8E%8B%E5%AE%88%E4%BB%81.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  shankar:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Raja_Ravi_Varma_-_Sankaracharya.jpg/330px-Raja_Ravi_Varma_-_Sankaracharya.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  ramanu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Ramanuja1920s.jpg/330px-Ramanuja1920s.jpg',
  madhva:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Shri_Madhvacharya_Vigraha%2C_Pajaka%2C_Udupi.jpg/330px-Shri_Madhvacharya_Vigraha%2C_Pajaka%2C_Udupi.jpg',
  nagarj:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Nagarjuna_with_84_mahasiddha_cropped.jpg/330px-Nagarjuna_with_84_mahasiddha_cropped.jpg',
  asanga:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Ashtamangala_Lotus.svg/330px-Ashtamangala_Lotus.svg.png',
  vasuba:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Vasubandhu.png/330px-Vasubandhu.png',
  dharma:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Tibet%2C_c._15th-16th_century_-_Portrait_of_Dharmakirti_-_2010.474_-_Cleveland_Museum_of_Art.tif/lossy-page1-330px-Tibet%2C_c._15th-16th_century_-_Portrait_of_Dharmakirti_-_2010.474_-_Cleveland_Museum_of_Art.tif.jpg',
  buddha:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg/330px-Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg',
  bodhid:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/BodhidharmaYoshitoshi1887.jpg/330px-BodhidharmaYoshitoshi1887.jpg',
  dogen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Soto-Zen-Master-Dogen-Zenji-Portrait.png/330px-Soto-Zen-Master-Dogen-Zenji-Portrait.png',
  nichir:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Nichiren_Daishonin_Hakii_Portrait.jpg/330px-Nichiren_Daishonin_Hakii_Portrait.jpg',
  honen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Takanobu-no-miei.jpg/330px-Takanobu-no-miei.jpg',
  shinran:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Shinran_%28Nara_National_Museum%29.jpg/330px-Shinran_%28Nara_National_Museum%29.jpg',
  ibnsin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Avicenna_Bust%2C_left_profile_%28cropped%29.jpg/330px-Avicenna_Bust%2C_left_profile_%28cropped%29.jpg',
  ibnrus:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Andrea_di_bonaiuto%2C_apotesosi_di_san_tommaso_d%27aquino%2C_11_averro%C3%A8.jpg/330px-Andrea_di_bonaiuto%2C_apotesosi_di_san_tommaso_d%27aquino%2C_11_averro%C3%A8.jpg',
  ibntuf:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Ibn_%E1%B9%ACufail%2C_Sayr_mulhimah_min_al-Sharq_wa-al-Gharb.png/330px-Ibn_%E1%B9%ACufail%2C_Sayr_mulhimah_min_al-Sharq_wa-al-Gharb.png',
  ibnarb:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/%D9%82%D8%A8%D8%B1_%D8%A7%D9%84%D8%B4%D9%8A%D8%AE_%D9%85%D8%AD%D9%8A%D9%8A_%D8%A7%D9%84%D8%AF%D9%8A%D9%86_%D8%A8%D9%86_%D8%B9%D8%B1%D8%A8%D9%8A.jpg/330px-%D9%82%D8%A8%D8%B1_%D8%A7%D9%84%D8%B4%D9%8A%D8%AE_%D9%85%D8%AD%D9%8A%D9%8A_%D8%A7%D9%84%D8%AF%D9%8A%D9%86_%D8%A8%D9%86_%D8%B9%D8%B1%D8%A8%D9%8A.jpg',
  alkind:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Stamp_IQ_1962_6f.jpg/330px-Stamp_IQ_1962_6f.jpg',
  alfara:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Alpharabius_in_Liber_Chronicarum_1493_AD.png/330px-Alpharabius_in_Liber_Chronicarum_1493_AD.png',
  ibnkha:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Bust_of_Ibn_Khaldun_%28Casbah_of_Bejaia%2C_Algeria%29.jpg/330px-Bust_of_Ibn_Khaldun_%28Casbah_of_Bejaia%2C_Algeria%29.jpg',
  schlei:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Friedrich_Daniel_Ernst_Schleiermacher.jpg/330px-Friedrich_Daniel_Ernst_Schleiermacher.jpg',
  herder:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Johann_Gottfried_Herder_2.jpg/330px-Johann_Gottfried_Herder_2.jpg',
  lessin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Gotthold_Ephraim_Lessing.PNG/330px-Gotthold_Ephraim_Lessing.PNG',
  jacobi:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Friedrich_Heinrich_Jacobi_portrait.jpg/330px-Friedrich_Heinrich_Jacobi_portrait.jpg',
  romano:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Portrait_of_Giordano_Bruno_in_%22Opere%22_Wellcome_L0015152_%28cropped%29.jpg/330px-Portrait_of_Giordano_Bruno_in_%22Opere%22_Wellcome_L0015152_%28cropped%29.jpg',
  copern:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Nikolaus_Kopernikus_MOT.jpg/330px-Nikolaus_Kopernikus_MOT.jpg',
  kepler: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/JKepler.jpg/330px-JKepler.jpg',
  newton:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Isaac_Blessing_Jacob_MET_DP145918_%28cropped_2%29.jpg/330px-Isaac_Blessing_Jacob_MET_DP145918_%28cropped_2%29.jpg',
  huygen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Christiaan_Huygens-painting.jpeg/330px-Christiaan_Huygens-painting.jpeg',
  priest:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Priestley_%28cropped%29.jpg/330px-Priestley_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  price:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_competitive_price_system_adapted_from_Samuelson%2C_1961.jpg/330px-The_competitive_price_system_adapted_from_Samuelson%2C_1961.jpg',
  fergus:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/ProfAdamFerguson.jpg/330px-ProfAdamFerguson.jpg',
  smith:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Adam_Smith_The_Muir_portrait.jpg/330px-Adam_Smith_The_Muir_portrait.jpg',
  mendel:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Moses_Mendelson_P7160073.JPG/330px-Moses_Mendelson_P7160073.JPG',
  comte:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Auguste_Comte.jpg/330px-Auguste_Comte.jpg',
  bentha:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Jeremy_Bentham_by_Henry_William_Pickersgill.jpg/330px-Jeremy_Bentham_by_Henry_William_Pickersgill.jpg',
  sidgwi:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Henry_Sidgwick_National_Portrait_Gallery_headshot_crop.png/330px-Henry_Sidgwick_National_Portrait_Gallery_headshot_crop.png',
  spence:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Herbert_Spencer.jpg/330px-Herbert_Spencer.jpg',
  royce:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Josiah_Royce.jpeg/330px-Josiah_Royce.jpeg',
  cooley:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Charles_Cooley.png/330px-Charles_Cooley.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  durkhe:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/%C3%89mile_Durkheim.jpg/330px-%C3%89mile_Durkheim.jpg',
  weber:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Max_Weber%2C_1918.jpg/330px-Max_Weber%2C_1918.jpg',
  simmel: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Simmel_01.JPG',
  pareto:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Vilfredo_Pareto_1870s2.jpg/330px-Vilfredo_Pareto_1870s2.jpg',
  mosca: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Gaetano_Mosca.gif',
  luxemb:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Rosa_Luxemburg_%28cropped%29.jpg/330px-Rosa_Luxemburg_%28cropped%29.jpg',
  lenin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Lenin_in_1920_%28cropped%29.jpg/330px-Lenin_in_1920_%28cropped%29.jpg',
  trotsk:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Leon_Trotsky_1918_%283x4_rotated_cropped_b%29.jpg/330px-Leon_Trotsky_1918_%283x4_rotated_cropped_b%29.jpg',
  fromm:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Erich_Fromm_1974.jpg/330px-Erich_Fromm_1974.jpg',
  arendt:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg/330px-Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg',
  hayek:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Friedrich_Hayek_portrait.jpg/330px-Friedrich_Hayek_portrait.jpg',
  mises:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Ludwig_von_Mises_%283x4_cropped%29.jpg/330px-Ludwig_von_Mises_%283x4_cropped%29.jpg',
  dworki:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Ronald_Dworkin_at_the_Brooklyn_Book_Festival.jpg/330px-Ronald_Dworkin_at_the_Brooklyn_Book_Festival.jpg',
  austin: 'https://upload.wikimedia.org/wikipedia/en/f/f1/J._L._Austin_%28philosopher%29_1951.jpg',
  grice:
    'https://upload.wikimedia.org/wikipedia/en/c/c4/Herbert_Paul_Grice%2C_philosopher%2C_%281913_%E2%80%93_1988%29_photograph.jpg',
  goodma: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Nelson_Goodman.jpg',
  sellars:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Wilfrid_Sellars_Faculty_Photo.jpg/330px-Wilfrid_Sellars_Faculty_Photo.jpg',
  smart: 'https://upload.wikimedia.org/wikipedia/en/1/17/JJC_Smart.jpg',
  feigl:
    'https://upload.wikimedia.org/wikipedia/en/3/39/Philosopher_Herbert_Feigl_%281902_%E2%80%931988%29_In_1973.jpg',
  flanag:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Owen_Flanagan.jpg/330px-Owen_Flanagan.jpg',
  church:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Patricia_Churchland%2C_2015_%28cropped%29.jpg/330px-Patricia_Churchland%2C_2015_%28cropped%29.jpg',
  vanfra:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/2018_Ford_Transit_Custom_300_Base_2.0_facelift.jpg/330px-2018_Ford_Transit_Custom_300_Base_2.0_facelift.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  feyer:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Paul_Feyerabend_Berkeley.jpg/330px-Paul_Feyerabend_Berkeley.jpg',
  lakato:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Professor_Imre_Lakatos%2C_c1960s.jpg/330px-Professor_Imre_Lakatos%2C_c1960s.jpg',
  russell:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Bertrand_Russell_smoking_in_1936.jpg/330px-Bertrand_Russell_smoking_in_1936.jpg',
  butler:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/White_House_Butlers_Pantry.jpg/330px-White_House_Butlers_Pantry.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  kriste:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Julia_Kristeva_%C3%A0_Paris_en_2008.jpg/330px-Julia_Kristeva_%C3%A0_Paris_en_2008.jpg',
  cixous:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/H%C3%A9l%C3%A8ne_Cixous_par_Claude_Truong-Ngoc_2011.jpg/330px-H%C3%A9l%C3%A8ne_Cixous_par_Claude_Truong-Ngoc_2011.jpg',
  spivak:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Gayatri_Spivak_on_Subversive_Festival.jpg/330px-Gayatri_Spivak_on_Subversive_Festival.jpg',
  fanon:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Photograph_of_Frantz_Fanon_from_Black_Skin_White_Masks_%281967%29_dust_jacket.webp/330px-Photograph_of_Frantz_Fanon_from_Black_Skin_White_Masks_%281967%29_dust_jacket.webp.png',
  cesair:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Aime_Cesaire_2003.jpg/330px-Aime_Cesaire_2003.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  sengh:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/UNESCO_History%2C_Visite_de_S._Exc._M._L%C3%A9opold_Sedar_Senghor%2C_Pr%C3%A9sident_de_la_R%C3%A9publique_du_S%C3%A9n%C3%A9gal_-_UNESCO_-_PHOTO0000002688_0001_%28cropped%29.tiff/lossy-page1-330px-UNESCO_History%2C_Visite_de_S._Exc._M._L%C3%A9opold_Sedar_Senghor%2C_Pr%C3%A9sident_de_la_R%C3%A9publique_du_S%C3%A9n%C3%A9gal_-_UNESCO_-_PHOTO0000002688_0001_%28cropped%29.tiff.jpg',
  wiredu: 'https://upload.wikimedia.org/wikipedia/en/d/db/Kwasi_Wiredu.jpg',
  hounto: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Hountondji_front.jpg',
  appiah:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Kwame_Anthony_Appiah_no_Fronteiras_do_Pensamento_Porto_Alegre_2013_%289517494881%29.jpg/330px-Kwame_Anthony_Appiah_no_Fronteiras_do_Pensamento_Porto_Alegre_2013_%289517494881%29.jpg',
  coates:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Ta-Nehisi_Coates_at_the_2025_Edinburgh_International_Book_Festival-21_%28cropped%29.jpg/330px-Ta-Nehisi_Coates_at_the_2025_Edinburgh_International_Book_Festival-21_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  hooks:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Bell_hooks%2C_October_2014.jpg/330px-Bell_hooks%2C_October_2014.jpg',
  collins:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/PatriciaHillCollins.jpg/330px-PatriciaHillCollins.jpg',
  lorde:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Lorde_Glasto2025-23_%28cropped%29.jpg/330px-Lorde_Glasto2025-23_%28cropped%29.jpg',
  wollst:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Mary_Wollstonecraft_Portrait.jpg/330px-Mary_Wollstonecraft_Portrait.jpg',
  simone:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Simone_Weil_1943.jpg/330px-Simone_Weil_1943.jpg',
  stein:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Edith_Stein_%28ca._1938-1939%29.jpg/330px-Edith_Stein_%28ca._1938-1939%29.jpg',
  nussba:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Martha_Nussbaum_2010_%28cropped%29.jpg/330px-Martha_Nussbaum_2010_%28cropped%29.jpg',
  young: 'https://upload.wikimedia.org/wikipedia/en/0/04/Iris_Marion_Young_photo.jpg',
  fraser:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/NancyFraser_%28cropped%29.JPG/330px-NancyFraser_%28cropped%29.JPG',
  haraway:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Donna_Haraway_2006_%28cropped%29.jpg/330px-Donna_Haraway_2006_%28cropped%29.jpg',
  hardin: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Garrett_Hardin.jpg',
  scanlo:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Kissel_Lecture_with_Philippe_Van_Parijs_%2841326690252%29.jpg/330px-Kissel_Lecture_with_Philippe_Van_Parijs_%2841326690252%29.jpg',
  adams:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/RobertMerrihewAdams20060625.jpg/330px-RobertMerrihewAdams20060625.jpg',
  vaninw:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/2018_Ford_Transit_Custom_300_Base_2.0_facelift.jpg/330px-2018_Ford_Transit_Custom_300_Base_2.0_facelift.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  xenoph:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Xenophanes_in_Thomas_Stanley_History_of_Philosophy.jpg/330px-Xenophanes_in_Thomas_Stanley_History_of_Philosophy.jpg',
  leucip:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Pinacoteca_Querini_Stampalia_-_Leucippus_-_Luca_Giordano.jpg/330px-Pinacoteca_Querini_Stampalia_-_Leucippus_-_Luca_Giordano.jpg',
  dubois:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/W.E.B._Du_Bois_by_James_E._Purdy%2C_1907_%283x4%29.jpg/330px-W.E.B._Du_Bois_by_James_E._Purdy%2C_1907_%283x4%29.jpg',
  depiz:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Christine_de_Pisan_-_cathedra.jpg/330px-Christine_de_Pisan_-_cathedra.jpg',
  philo:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/San_Stefano_Grand_Plaza.JPG/330px-San_Stefano_Grand_Plaza.JPG',
  origen: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Origen.jpg/330px-Origen.jpg',
  tertul:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Tertullian2.png/330px-Tertullian2.png',
  clemen:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/San_Stefano_Grand_Plaza.JPG/330px-San_Stefano_Grand_Plaza.JPG',
  basili:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Basil_of_Caesarea.jpg/330px-Basil_of_Caesarea.jpg',
  gregor:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Gregory_of_Nyssa.jpg/330px-Gregory_of_Nyssa.jpg',
  johnch:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Johnchrysostom.jpg/330px-Johnchrysostom.jpg',
  jerome:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/MatthiasStom-SaintJerome-Nantes.jpg/330px-MatthiasStom-SaintJerome-Nantes.jpg',
  isidor:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Sevilla_Cathedral_-_Southeast.jpg/330px-Sevilla_Cathedral_-_Southeast.jpg',
  alcuin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Raban-Maur_Alcuin_Otgar.jpg/330px-Raban-Maur_Alcuin_Otgar.jpg',
  petrard:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Portrait_of_Francesco_Petrarca_%28called_Petrarch%29_-_French_school%2C_17th_century.jpg/330px-Portrait_of_Francesco_Petrarca_%28called_Petrarch%29_-_French_school%2C_17th_century.jpg',
  boccac:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Andrea_del_Castagno_Giovanni_Boccaccio_c_1450.jpg/330px-Andrea_del_Castagno_Giovanni_Boccaccio_c_1450.jpg',
  machia:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Portrait_of_Niccol%C3%B2_Machiavelli_by_Santi_di_Tito.jpg/330px-Portrait_of_Niccol%C3%B2_Machiavelli_by_Santi_di_Tito.jpg',
  zwingl:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Ulrich-Zwingli-1.jpg/330px-Ulrich-Zwingli-1.jpg',
  melanc:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Portrait_of_Philipp_Melanchthon_%281497%E2%80%931560%29%2C_by_Lucas_Cranach_the_Elder_-_Gem%C3%A4ldegalerie_Alte_Meister%2C_Kassel.jpg/330px-Portrait_of_Philipp_Melanchthon_%281497%E2%80%931560%29%2C_by_Lucas_Cranach_the_Elder_-_Gem%C3%A4ldegalerie_Alte_Meister%2C_Kassel.jpg',
  servet:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Michael_Servetus.jpg/330px-Michael_Servetus.jpg',
  bruno:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Portrait_of_Giordano_Bruno_in_%22Opere%22_Wellcome_L0015152_%28cropped%29.jpg/330px-Portrait_of_Giordano_Bruno_in_%22Opere%22_Wellcome_L0015152_%28cropped%29.jpg',
  grotiu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Michiel_Jansz_van_Mierevelt_-_Hugo_Grotius.jpg/330px-Michiel_Jansz_van_Mierevelt_-_Hugo_Grotius.jpg',
  moreh:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Henry_More_Yale_illustration.jpg/330px-Henry_More_Yale_illustration.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  feuerb:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Ludwig_Feuerbach-1.2_V01-1.1.1_cropped_and_rotated.jpg/330px-Ludwig_Feuerbach-1.2_V01-1.1.1_cropped_and_rotated.jpg',
  bakuni:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Mikhail_Bakunin_Nader_%283x4_cropped%29.jpg/330px-Mikhail_Bakunin_Nader_%283x4_cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail',
  kropot:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Peter_Kropotkin_circa_1900.jpg/330px-Peter_Kropotkin_circa_1900.jpg',
  sextus:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Sexti_Empirici_Adversus_mathematicos.djvu/page1-330px-Sexti_Empirici_Adversus_mathematicos.djvu.jpg',
  carnea:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Carneades_bust.jpg/330px-Carneades_bust.jpg',
  arcesi:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Arcesilaus_and_Carneades.jpg/330px-Arcesilaus_and_Carneades.jpg',
  panait:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Panaetius_Nuremberg_Chronicle.jpg/330px-Panaetius_Nuremberg_Chronicle.jpg',
  posido:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Posidonio%2C_replica_augustea_%2823_ac.-14_dc_ca%29_da_originale_del_100-50_ac._ca._6142.JPG/330px-Posidonio%2C_replica_augustea_%2823_ac.-14_dc_ca%29_da_originale_del_100-50_ac._ca._6142.JPG',
  asclep:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Asclepio_di_tralle%2C_commentario_al_libro_alpha_meizon_della_metafisica_di_aristotele_%28in_greco%29%2C_corf%C3%B9_1564_%28pluteo_86.11%29.jpg/330px-Asclepio_di_tralle%2C_commentario_al_libro_alpha_meizon_della_metafisica_di_aristotele_%28in_greco%29%2C_corf%C3%B9_1564_%28pluteo_86.11%29.jpg',
  petera:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Piotr_Abelard_%28cropped%29.jpg/330px-Piotr_Abelard_%28cropped%29.jpg',
  bernar:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/San_Bernardo%2C_de_Juan_Correa_de_Vivar_%28Museo_del_Prado%29.jpg/330px-San_Bernardo%2C_de_Juan_Correa_de_Vivar_%28Museo_del_Prado%29.jpg',
  thomas:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/St-thomas-aquinasFXD.jpg/330px-St-thomas-aquinasFXD.jpg',
  cohen: 'https://upload.wikimedia.org/wikipedia/en/8/82/Philosopher_G._A._Cohen_in_1986.jpg',
  walzer:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/MichaelWalzer-USNA-Lecture.jpg/330px-MichaelWalzer-USNA-Lecture.jpg',
  sorabj:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Richard_I_of_England.png/330px-Richard_I_of_England.png',
  annas:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Duccio_di_Buoninsegna_-_Christ_before_Annas.jpg/330px-Duccio_di_Buoninsegna_-_Christ_before_Annas.jpg',
  irwin:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Portrait_of_Terence_from_Vaticana%2C_Vat._lat.jpg/330px-Portrait_of_Terence_from_Vaticana%2C_Vat._lat.jpg',
  vlasto:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Vlasto_Coat_of_Arms.jpg/330px-Vlasto_Coat_of_Arms.jpg',
  burnye: 'https://upload.wikimedia.org/wikipedia/en/e/e9/Myles_Fredric_Burnyeat.jpg',
  sedley:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/King_David%2C_the_King_of_Israel.jpg/330px-King_David%2C_the_King_of_Israel.jpg',
  grote:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Thomas_Stewardson_%281781-1859%29_-_George_Grote_-_NPG_365_-_National_Portrait_Gallery.jpg/330px-Thomas_Stewardson_%281781-1859%29_-_George_Grote_-_NPG_365_-_National_Portrait_Gallery.jpg',
  grotes:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Thomas_Stewardson_%281781-1859%29_-_George_Grote_-_NPG_365_-_National_Portrait_Gallery.jpg/330px-Thomas_Stewardson_%281781-1859%29_-_George_Grote_-_NPG_365_-_National_Portrait_Gallery.jpg',
};
